CALL CSVWRITE(@PATH_OUTPUT ||'unidad_medida.csv',
'SELECT INTIDUNIDMED AS ID, VCCVEUNIDMED AS referenceId, VCDESCUNIDMED AS name, TRUE AS countable FROM UNIDADMEDIDA WHERE INTIDUNIDMED NOT IN (14, 15)
 UNION
 SELECT INTIDUNIDMED AS ID, VCCVEUNIDMED AS referenceId, VCDESCUNIDMED AS name, FALSE AS countable FROM UNIDADMEDIDA WHERE INTIDUNIDMED IN (14, 15)
 ORDER BY 1',
'CHARSET=UTF-8');