CALL CSVWRITE(@PATH_OUTPUT ||'producto.csv',
'SELECT VCCODIGOBARRAS AS ID, VCPLU AS REFERENCEID, VCDESCPROD AS NAME, '''' AS IMAGE, ''ITEM'' AS PRODUCTTYPE, VCTIPOPRODUCTO AS productCategory, INTIDUNIDMED AS productMeasureUnit FROM PRODUCTO',
'CHARSET=UTF-8');
