//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.10.17 at 06:19:12 AM PDT
//

package com.toolinc.openairmarket.etl.pipeline.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for transformations complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="transformations"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inputs" type="{http://www.openairmarket.etl.pipeline.model}inputs"/&gt;
 *         &lt;element name="conversions" type="{http://www.openairmarket.etl.pipeline.model}conversions"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "transformations",
    propOrder = {"inputs", "conversions"})
public class Transformations {

  @XmlElement(required = true)
  protected Inputs inputs;

  @XmlElement(required = true)
  protected Conversions conversions;

  /**
   * Gets the value of the inputs property.
   *
   * @return possible object is {@link Inputs }
   */
  public Inputs getInputs() {
    return inputs;
  }

  /**
   * Sets the value of the inputs property.
   *
   * @param value allowed object is {@link Inputs }
   */
  public void setInputs(Inputs value) {
    this.inputs = value;
  }

  /**
   * Gets the value of the conversions property.
   *
   * @return possible object is {@link Conversions }
   */
  public Conversions getConversions() {
    return conversions;
  }

  /**
   * Sets the value of the conversions property.
   *
   * @param value allowed object is {@link Conversions }
   */
  public void setConversions(Conversions value) {
    this.conversions = value;
  }
}
